# frozen_string_literal: true
# rubocop:disable LineLength
module DiffHelperTestSeedContent
  M1 = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam pretium eros augue, ac fermentum massa fringilla id. Mauris malesuada feugiat efficitur. Nam elementum augue id eros fermentum, a congue turpis tincidunt. Curabitur posuere nibh eget ligula viverra, id consectetur nisi condimentum. Nulla placerat, odio pretium facilisis lacinia, nunc est efficitur sem, vitae iaculis justo ante quis massa. Suspendisse ligula est, dictum gravida neque a, vulputate tristique odio. Pellentesque placerat ex et dui aliquam viverra. Vivamus commodo mi in velit vehicula cursus. Donec faucibus risus vel libero rhoncus, egestas hendrerit augue dapibus. Suspendisse ac dapibus sapien. Donec rutrum lorem eleifend, posuere diam ornare, lobortis lacus. Morbi lobortis nisl nec enim auctor, quis blandit justo venenatis. Phasellus mattis dolor vel porta semper. Nullam vel felis mattis, commodo risus sit amet, porta ligula. Donec semper non nisl fringilla elementum.'

  M2 = "Pellentesque vel odio turpis. Ut non sem et eros mattis rhoncus at ac nisl. Aliquam erat volutpat. Sed sit amet pretium quam. Ut facilisis sodales ligula, sit amet vulputate libero egestas at. Sed pellentesque elit id finibus semper. Integer eu facilisis magna, et placerat tortor. Aliquam erat volutpat. Cras porttitor, magna non imperdiet cursus, leo elit ornare eros, id bibendum leo felis at leo. Donec augue mi, aliquam ac quam a, egestas eleifend neque.\n Quisque rutrum faucibus nibh vitae elementum. Integer ultricies sodales erat, ut commodo ante. Nam eu urna non quam congue egestas. Pellentesque congue, lectus non rutrum porttitor, orci dui lacinia lectus, vel consectetur turpis sapien sed risus. Phasellus non leo ac dolor porttitor bibendum faucibus eu odio. Vestibulum sodales sed ipsum et varius. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed sit amet ipsum eget neque egestas suscipit."

  M3 = "Pellentesque vel odio turpis. Ut non sem et eros mattis rhoncus at ac nisl. Aliquam erat volutpat. Sed sit amet pretium quam. Ut facilisis sodales ligula, sit amet vulputate libero egestas at. Sed pellentesque elit id finibus semper. Integer eu facilisis magna, et placerat tortor. Aliquam erat volutpat. Cras porttitor, magna non imperdiet cursus, leo elit ornare eros, id bibendum leo felis at leo. Donec augue mi, aliquam ac quam a, egestas eleifend neque. \nQuisque rutrum faucibus nibh vitae elementum. Integer ultricies sodales erat, ut commodo ante. Nam eu urna non quam congue egestas. Pellentesque congue, lectus non rutrum porttitor, orci dui lacinia lectus, vel consectetur turpis sapien sed risus. Phasellus non leo ac dolor porttitor bibendum faucibus eu odio. Vestibulum sodales sed ipsum et varius. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed sit amet ipsum eget neque egestas suscipit. \nFusce et tellus at massa elementum viverra at in nisi. Donec commodo cursus ultrices. Nulla sollicitudin, nisi nec rutrum sodales, felis orci porttitor odio, eget tristique ante sapien non nibh. Aenean commodo gravida ante, et ultrices mi. In condimentum id nisi sit amet dapibus. Donec sodales, ex eu euismod viverra, tortor ex fermentum felis, at sagittis ex orci eget nibh. Integer non nulla nunc. Nullam ac lobortis mauris, eget auctor neque. Curabitur in vehicula enim, quis consequat metus. Suspendisse potenti. Ut tempor ante et dolor scelerisque, sed viverra ante commodo. Morbi convallis mauris nec risus tristique lacinia. Donec consectetur magna eget quam condimentum accumsan. Sed nec rhoncus dui."

  M4 = 'Sed consectetur lacus sed mauris gravida, eu fringilla turpis congue. Praesent varius diam vel justo aliquam consequat. Fusce dapibus scelerisque tincidunt. Nunc lorem libero, auctor sed diam nec, egestas rhoncus ipsum. In cursus odio sed augue volutpat, semper vulputate lorem egestas. Morbi laoreet elit id eleifend consectetur. Etiam convallis ac nulla eu rhoncus. Ut a purus neque. Morbi eu dui eros. Vivamus fermentum felis quis tempor accumsan. Vestibulum at bibendum lorem.'
end
